[package]
name = "job_abstrs"
version = "0.1.0"
edition = "2021"
description = "Abstractions for event-driven jobs."
license = "MIT"

[dependencies]
async-trait = "0.1.77"
either = "1.10.0"
thiserror = "1.0.58"
tokio = { version = "1.36.0", features = ["full"] }
